// Snapshot the corpus into the site: the six explorer CSVs, plus the headline
// numbers as generated JSON.
//
// Why this exists. Both halves used to be done by hand, and both drifted:
//
//   - public/data/*.csv was last copied 2026-08-10 10:58. Row counts still
//     matched, so nothing looked wrong, but the questions sheets were missing
//     `instruction`, `option_d` and `option_e`, and French vocabulary was
//     missing `translation` and `gender` -- i.e. the rubric backfill and the
//     4,303 recovered translations were absent from the Explorer entirely.
//   - lib/data.ts carried French as 511 pages / 326 transcribed / 263 verified
//     when the corpus held 584 / 584 / 548. The site understated its own
//     completion as 78% verified when it was 97%.
//
// The stale numbers even sat under a comment promising they were "COMPUTED ...
// so it can't silently drift" -- true of the rollup, but it was derived from
// hand-typed aggregates, so it inherited their staleness. Hence: generate the
// aggregates too, not just the thing built from them.
//
// Run from site-next/:  npm run sync:corpus
//
// Deliberately NOT part of `next build`. README commits this directory to being
// self-contained, with the corpus snapshotted rather than read from the parent
// tree at build time, and Vercel's Root Directory is site-next -- the corpus is
// not even present there. This writes files that are then committed.

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const SITE = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const REPO = path.dirname(SITE);

const SOURCES = {
  french: {
    root: path.join(REPO, "french", "extracted"),
    csv: {
      catalog: "french-catalog-all.csv",
      questions: "french-questions-all.csv",
      vocabulary: "french-vocabulary-all.csv",
    },
  },
  german: {
    root: path.join(REPO, "german", "extracted"),
    csv: {
      catalog: "german-a1-catalog-all.csv",
      questions: "german-a1-questions-all.csv",
      vocabulary: "german-a1-vocabulary-all.csv",
    },
  },
};

// Count records, not lines: a quoted field may contain newlines, and several
// question rows do. Counting "\n" would overcount them.
function countCsvRecords(text) {
  let rows = 0;
  let inQuotes = false;
  let sawContent = false;
  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    if (inQuotes) {
      if (ch === '"') {
        if (text[i + 1] === '"') i++;
        else inQuotes = false;
      }
      continue;
    }
    if (ch === '"') { inQuotes = true; sawContent = true; continue; }
    if (ch === "\n") {
      if (sawContent) rows++;
      sawContent = false;
      continue;
    }
    if (ch !== "\r") sawContent = true;
  }
  if (sawContent) rows++;
  return Math.max(0, rows - 1); // drop the header
}

function csvHeader(text) {
  const nl = text.indexOf("\n");
  return (nl === -1 ? text : text.slice(0, nl)).replace(/^﻿/, "").trim().split(",");
}

// Registered, non-legacy books. `pipeline: legacy-manifest` books predate the
// shared engine, are excluded from the deliverable, and must not inflate the
// site's totals -- conjugaison-a1-a2 alone would add 104 pages of which only 60
// are transcribed.
function engineCollections(root) {
  const cfg = JSON.parse(readFileSync(path.join(root, "_tools", "collections.json"), "utf-8"));
  return cfg.collections.filter((c) => c.pipeline !== "legacy-manifest");
}

function pageStats(root, slug) {
  const dir = path.join(root, slug, "pages");
  if (!existsSync(dir)) return null;
  const pages = readdirSync(dir).filter((f) => /^page-\d+\.md$/.test(f));
  if (!pages.length) return null;
  let verified = 0, transcribed = 0, qaPass = 0, qaFail = 0;
  for (const f of pages) {
    const head = readFileSync(path.join(dir, f), "utf-8").slice(0, 600);
    const status = /^status:\s*(\S+)/m.exec(head)?.[1];
    const qa = /^qa:\s*(\S+)/m.exec(head)?.[1];
    if (status === "verified") verified++;
    if (status === "verified" || status === "transcribed") transcribed++;
    if (qa === "pass") qaPass++;
    else if (qa === "fail") qaFail++;
  }
  return { pages: pages.length, verified, transcribed, qaPass, qaFail };
}

const out = { note: "GENERATED by scripts/sync-corpus.mjs -- do not hand-edit.", languages: {} };
let copied = 0;

for (const [lang, src] of Object.entries(SOURCES)) {
  const destDir = path.join(SITE, "public", "data", lang);
  mkdirSync(destDir, { recursive: true });

  const totals = { books: 0, pages: 0, transcribed: 0, verified: 0, qaPass: 0, qaFail: 0 };
  for (const c of engineCollections(src.root)) {
    const s = pageStats(src.root, c.slug);
    if (!s) continue;
    totals.books++;
    for (const k of ["pages", "transcribed", "verified", "qaPass", "qaFail"]) totals[k] += s[k];
  }

  for (const [type, filename] of Object.entries(src.csv)) {
    const from = path.join(src.root, filename);
    if (!existsSync(from)) throw new Error(`missing corpus export: ${from}`);
    const text = readFileSync(from, "utf-8");
    writeFileSync(path.join(destDir, `${type}.csv`), text);
    copied++;
    const n = countCsvRecords(text);
    if (type === "questions") totals.questions = n;
    if (type === "vocabulary") totals.vocabulary = n;
    console.log(`  ${lang}/${type}.csv  ${n} rows, ${csvHeader(text).length} columns`);
  }

  out.languages[lang] = totals;
}

const f = out.languages.french, g = out.languages.german;
out.combined = {
  sets: f.books + g.books,
  pages: f.pages + g.pages,
  transcribed: f.transcribed + g.transcribed,
  verified: f.verified + g.verified,
  qaPass: f.qaPass + g.qaPass,
  qaFail: f.qaFail + g.qaFail,
};

writeFileSync(
  path.join(SITE, "lib", "corpus-stats.generated.json"),
  JSON.stringify(out, null, 2) + "\n",
);

console.log(`\n${copied} CSV(s) synced.`);
console.log("combined:", JSON.stringify(out.combined));
