#!/usr/bin/env python
"""Assemble a clean, content-team-friendly deliverable tree under _exports/.

Non-destructive: COPIES the already-generated per-collection sheets + unified
docs + the combined roll-up sheets into a tidy publisher-grouped layout. The
in-collection originals (including the FROZEN Goethe files) are never moved or
modified. Re-runnable — wipes and rebuilds _exports/ each time.

Layout (per the chosen "by publisher + combined" structure):

  _exports/
    README.md
    _combined/
      german-a1-{catalog,questions,vocabulary}-all.csv      (global)
      <family>-a1-{catalog,questions,vocabulary}-all.csv    (per publisher)
    <family>/<collection>/
      <collection>.md
      <collection>-catalog.csv
      <collection>-questions.csv      (only if the collection has one)
      <collection>-vocabulary.csv     (only if the collection has one)

Usage:  python _tools/package_exports.py
"""
import csv
import glob
import json
import os
import shutil

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)               # german/extracted/
OUT = os.path.join(ROOT, '_exports')
CONFIG = os.path.join(TOOLS, 'collections.json')
KINDS = ['catalog', 'questions', 'vocabulary']


def rows_in(path):
    if not os.path.exists(path):
        return 0
    with open(path, encoding='utf-8-sig', newline='') as f:
        return max(0, sum(1 for _ in f) - 1)


def main():
    cols = json.load(open(CONFIG, encoding='utf-8'))['collections']
    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(os.path.join(OUT, '_combined'), exist_ok=True)

    # 1. combined roll-up sheets (global + per-family), copied read-only
    combined = []
    for f in sorted(glob.glob(os.path.join(ROOT, '*-a1-*-all.csv'))):
        shutil.copy2(f, os.path.join(OUT, '_combined', os.path.basename(f)))
        combined.append((os.path.basename(f), rows_in(f)))

    # 2. per-collection deliverables, grouped by publisher family
    per_family = {}
    manifest = []
    for c in cols:
        slug, fam = c['slug'], c.get('family', 'german')
        dest = os.path.join(OUT, fam, slug)
        srcdir = os.path.join(ROOT, slug)
        copied = {}
        os.makedirs(dest, exist_ok=True)
        md = os.path.join(srcdir, '%s.md' % slug)
        if os.path.exists(md):
            shutil.copy2(md, os.path.join(dest, '%s.md' % slug))
            copied['md'] = True
        for kind in KINDS:
            src = os.path.join(srcdir, '%s-%s.csv' % (slug, kind))
            if os.path.exists(src):
                shutil.copy2(src, os.path.join(dest, os.path.basename(src)))
                copied[kind] = rows_in(src)
        per_family.setdefault(fam, []).append((slug, c.get('title', slug), copied))
        manifest.append((fam, slug, c.get('title', slug), copied))

    # 3. README
    lines = [
        '# German A1 — Extraction Deliverables', '',
        'Clean, content-team-ready exports. **All CSVs are UTF-8 with BOM** so German',
        'umlauts (ä ö ü ß) render correctly on double-click in Excel / Google Sheets.',
        '', '## How this is organised', '',
        '- `_combined/` — roll-up sheets: **global** `german-a1-*` (every book) and',
        '  **per-publisher** `goethe-a1-*` / `netzwerk-a1-*` / `goyal-a1-*`.',
        '- `<publisher>/<book>/` — the four deliverables for one book:',
        '  the unified `.md`, and `-catalog` / `-questions` / `-vocabulary` CSVs',
        '  (a book only has the sheets that apply to it).', '',
        '## Sheet columns', '',
        '- **catalog** — one row per page: section, content type, activity, topic, level, status, word count, summary.',
        '- **questions** — one row per item: section, teil, item, item_type, question, option_a/b/c, correct_answer, topic, source_page.',
        '- **vocabulary** — one row per word: word, article, plural, word_class, example, topic, source_page.',
        '', '## Combined sheets', '',
        '| Sheet | Rows |', '|---|---|',
    ]
    for name, n in combined:
        lines.append('| `_combined/%s` | %d |' % (name, n))
    lines += ['', '## Books', '', '| Publisher | Book | Pages | Questions | Words |', '|---|---|---|---|---|']
    for fam, slug, title, copied in manifest:
        lines.append('| %s | %s | %s | %s | %s |' % (
            fam, title,
            copied.get('catalog', '—'),
            copied.get('questions', '—') or '—',
            copied.get('vocabulary', '—') or '—'))
    lines += ['', '_Generated by `_tools/package_exports.py` — re-run to refresh._', '']
    with open(os.path.join(OUT, 'README.md'), 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print('Built _exports/ :')
    print('  _combined/ : %d roll-up sheets' % len(combined))
    for fam in sorted(per_family):
        print('  %-10s : %d books' % (fam, len(per_family[fam])))
    total_csv = len(glob.glob(os.path.join(OUT, '**', '*.csv'), recursive=True))
    total_md = len(glob.glob(os.path.join(OUT, '**', '*.md'), recursive=True))
    print('  total: %d CSV + %d MD files' % (total_csv, total_md))


if __name__ == '__main__':
    main()
